import asyncio

from pydantic import BaseModel, Field

from sentinel.detection.pii import PIIDetector
from sentinel.detection.secrets import SecretsDetector
from sentinel.detection.toxicity import ToxicityDetector
from sentinel.exceptions import PolicyViolationError


class OutputGuardResult(BaseModel):
    """Outcome payload generated by the post-LLM output verification guardrail.

    Attributes:
        allowed: True if response is safe for delivery to the end user.
        processed_text: Final sanitized, deanonymized, or watermarked response text.
        blocked: True if response was halted due to data leakage or toxicity.
        redacted: True if sensitive leaked items were redacted in-place.
        leakage_detected: True if proprietary secrets or credentials were discovered.
        watermarked: True if cryptographic watermarking was attached.
        reason: Explanatory justification for blocking or redaction.
    """

    allowed: bool
    processed_text: str
    blocked: bool
    redacted: bool = Field(default=False)
    leakage_detected: bool = Field(default=False)
    watermarked: bool = Field(default=False)
    reason: str | None = Field(default=None)


class OutputGuard:
    """Post-LLM guardrail preventing credential leakage and restoring anonymized tokens.

    Attributes:
        secrets_detector: Credential and API key leakage detector.
        toxicity_detector: Response toxicity evaluation module.
        pii_detector: Entity extractor and deanonymizer.
        enable_watermarking: Whether to append steganographic watermarks.
    """

    def __init__(
        self,
        secrets_detector: SecretsDetector | None = None,
        toxicity_detector: ToxicityDetector | None = None,
        pii_detector: PIIDetector | None = None,
        enable_watermarking: bool = False,
    ) -> None:
        """Initialize OutputGuard.

        Args:
            secrets_detector: Custom or default SecretsDetector.
            toxicity_detector: Custom or default ToxicityDetector.
            pii_detector: Custom or default PIIDetector.
            enable_watermarking: Whether to embed invisible watermarks.

        Returns:
            None

        Raises:
            None

        Examples:
            >>> og = OutputGuard()
            >>> og.enable_watermarking
            False
        """
        self.secrets_detector: SecretsDetector = (
            secrets_detector if secrets_detector is not None else SecretsDetector()
        )
        self.toxicity_detector: ToxicityDetector = (
            toxicity_detector if toxicity_detector is not None else ToxicityDetector()
        )
        self.pii_detector: PIIDetector = (
            pii_detector if pii_detector is not None else PIIDetector()
        )
        self.enable_watermarking: bool = enable_watermarking

    def _apply_watermark(self, text: str) -> str:
        """Append invisible zero-width steganographic mark to the response.

        Args:
            text: Clean text string.

        Returns:
            str: Watermarked text string.

        Raises:
            None

        Examples:
            >>> pass
        """
        watermark_sequence = "\u200b\u200c\u200d"
        return f"{text}{watermark_sequence}"

    async def guard(
        self,
        text: str,
        anonymization_mapping: dict[str, str] | None = None,
        deanonymize: bool = True,
        raise_on_block: bool = False,
    ) -> OutputGuardResult:
        """Verify LLM generated response against leakage and restore original tokens.

        Args:
            text: Raw LLM output response.
            anonymization_mapping: Token map generated during input guard phase.
            deanonymize: Whether to restore tokens to original values.
            raise_on_block: Whether to raise PolicyViolationError on violations.

        Returns:
            OutputGuardResult: Sanitization status and final delivery text.

        Raises:
            PolicyViolationError: If leakage or toxicity triggers blocking.

        Examples:
            >>> import asyncio
            >>> og = OutputGuard()
            >>> res = asyncio.run(og.guard("Here is the answer."))
            >>> res.allowed
            True
        """
        sec_res = await self.secrets_detector.detect(text)
        if sec_res.detected:
            if raise_on_block:
                raise PolicyViolationError(
                    "Output blocked: credential leakage discovered",
                    policy_name="output_secret_leak_prevention",
                    action_taken="block",
                )
            return OutputGuardResult(
                allowed=False,
                processed_text="[REDACTED: Output contained confidential credentials]",
                blocked=True,
                leakage_detected=True,
                reason="Credential leakage prevented",
            )

        tox_res = await self.toxicity_detector.detect(text)
        if tox_res.detected:
            if raise_on_block:
                raise PolicyViolationError(
                    "Output blocked: toxic content in response",
                    policy_name="output_toxicity_prevention",
                    action_taken="block",
                )
            return OutputGuardResult(
                allowed=False,
                processed_text="[REDACTED: Output contained prohibited content]",
                blocked=True,
                reason="Toxic content filtered",
            )

        final_text = text
        if deanonymize and anonymization_mapping:
            final_text = self.pii_detector.deanonymize(text, anonymization_mapping)

        watermarked = False
        if self.enable_watermarking:
            final_text = self._apply_watermark(final_text)
            watermarked = True

        return OutputGuardResult(
            allowed=True,
            processed_text=final_text,
            blocked=False,
            watermarked=watermarked,
            reason="Output validated successfully",
        )

    def guard_sync(
        self,
        text: str,
        anonymization_mapping: dict[str, str] | None = None,
        deanonymize: bool = True,
        raise_on_block: bool = False,
    ) -> OutputGuardResult:
        """Synchronous wrapper for executing output guardrail inspection.

        Args:
            text: Output text to evaluate.
            anonymization_mapping: Map of tokens to original values.
            deanonymize: Restore tokens to real entities.
            raise_on_block: Raise PolicyViolationError if blocked.

        Returns:
            OutputGuardResult: Verified output status.

        Raises:
            PolicyViolationError: If blocked and raise_on_block is True.

        Examples:
            >>> og = OutputGuard()
            >>> res = og.guard_sync("Valid text")
            >>> res.allowed
            True
        """
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop is not None and loop.is_running():
            future = asyncio.run_coroutine_threadsafe(
                self.guard(text, anonymization_mapping, deanonymize, raise_on_block),
                loop,
            )
            return future.result()
        return asyncio.run(
            self.guard(text, anonymization_mapping, deanonymize, raise_on_block)
        )
